version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app  # Map the current directory (.) to /app inside the container
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
