name: CICD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true

     
      - name: Run docker container with env vars
        run: |
          docker run -d -p 3000:3000 \
            --name nodejs-app-container \
            -e PORT=${{ secrets.PORT }} \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest